# 排序

素材：
1. [史上最简单十大排序算法（Python实现）](https://blog.csdn.net/weixin_41571493/article/details/81875088)
2. [Python实现十大经典排序算法](https://www.jianshu.com/p/bbbab7fa77a2)
3. [Python实现十三大查找和排序算法](https://blog.csdn.net/Asher117/article/details/89500637)
4. [All Algorithms implemented in Python](https://github.com/TheAlgorithms/Python)

## 排序的分类 与 相关概念

**是否使用额外空间**：
- 内部排序：只使用内存
- 外部排序：内存和外存同时使用

**时间复杂度**：
- 非线性时间比较类排序：通过比较来决定元素间的相对次序，由于其时间复杂度不能突破O(nlogn)，因此称为非线性时间比较类排序、
- 线性时间非比较类排序： 不通过比较来决定元素间的相对次序，它可以突破基于比较排序的时间下界，以线性时间运行，因此称为线性时间非比较类排序。

**相关概念：**
- 稳定：如果a=b，排序不改变他们原始的次序
- 时间复杂度：对于排序数据的总的操作次数与n的关系
- 空间复杂度：算法执行时所需要的储存空间大小与n的关系

### 冒泡排序 Bubble Sort

> 思想：
1. 比较相邻的元素，如果第一个比第二个更大，那么交换他们两
2. 对每一对相邻的元素做同样的操作，从最开始的前两个数，到最后两个数。这样排在最后的数会是整个数列中最大的
3. 对数列重复以上操作，排除最后一个已经被排好序的数字。
4. 重复1-3，直到排序完成

冒泡排序对n个数据操作n-1轮，每一轮能找到一个最大值。

操作只对相邻两个数进行比较与交换，每一轮能把最值交换到数据的列尾，就像冒泡一样。

每一轮操作O(n)次，共O(n)轮，所以时间复杂度是O(n^2)

额外空间开销出现在交换数据的时候，需要一个过渡空间，空间复杂度是O(1)

In [7]:
import numpy as np
def BubbleSort(arr):
    n = len(arr)
    if n <= 1:
        return arr
    else:
        for i in range(n):
            for j in range(n-i-1):
                if arr[j] > arr[j+1]:
                    arr[j+1],arr[j] = arr[j],arr[j+1]
        return arr

In [27]:
def test_case(method,arr):
    print('排序前的数列：\n',np.array(arr))
    print('排序后的数列：\n',np.array(method(arr)))
    

In [28]:
test_case(BubbleSort,[1, 3, 4, -1])

排序前的数列：
 [ 1  3  4 -1]
排序后的数列：
 [-1  1  3  4]


### 快速排序 Quick Sort

> 思想
- 从数列中挑选一个元素，称为基准(pivot)
- 重新排序数列，所有比基准值小的元素摆放在基准的前面，所有比基准值大的元素摆放在基准的后面，相同的数可以摆放到任意一边。在这个分区退出之后，该基准就处于数列的中间位置。这个称为分区(partition)操作
- 递归地把小于基准的子数列和大于基准的子数列进行排序

快速排序基于选择划分，是简单选择排序的优化。

每次划分将数据宣导基准值的两边，然后递归对于两侧的数据进行划分，类似于二分法。

算法的整体性能取决于划分的平均程度，也即基准值的选择，从而衍生出快速排序的很多优化方案，甚至可以划分成多块。

基准值如果能把数据分为平均的两块，划分数为O(logn)，每次划分遍历一遍需要O(n)，时间复杂度是O(nlogn)

额外空间需要储存基准值，O(logn)次划分需要O(logn)个，空间复杂度O(logn)

In [38]:
# 空间复杂度O(nlogn)
def QuickSort(arr):
    if len(arr) <= 1:
        return arr
    else:
        mid = arr[0]
        left = [i for i in arr[1:] if i <= mid]
        right = [i for i in arr[1:] if i > mid]
        return QuickSort(left) + [mid] + QuickSort(right)

In [39]:
test_case(QuickSort,arr = list(np.random.randint(0,1000,size = 10)))

排序前的数列：
 [337  72 935 772 771 424 104 445 556 304]
排序后的数列：
 [ 72 104 304 337 424 445 556 771 772 935]


In [58]:
# 空间复杂度O(logn)
'''
@param nums: 待排序数组
@param left: 数组上界
@param right: 数组下界
'''
def QuickSort2(nums, left, right):  # 这种写法的平均空间复杂度为 O(logn) 
    # 分区操作
    def partition(nums, left, right):
        print(nums)
        print('\r\n')
        pivot = nums[left]  # 基准值
        while left < right:
            while left < right and nums[right] >= pivot:
                right -= 1
            nums[left] = nums[right]  # 比基准小的交换到前面
            print(nums)
            while left < right and nums[left] <= pivot:
                left += 1
            nums[right] = nums[left]  # 比基准大交换到后面
            print(nums)
        nums[left] = pivot # 基准值的正确位置，也可以为 nums[right] = pivot
        return left  # 返回基准值的索引，也可以为 return right
    # 递归操作
    if left < right:
        pivotIndex = partition(nums, left, right)
        quickSort2(nums, left, pivotIndex - 1)  # 左序列
        quickSort2(nums, pivotIndex + 1, right) # 右序列
    return nums

In [59]:
QuickSort2(np.random.randint(0,100,10),0,9)

[12 31 36 31 70 84 21 88 12 81]


[12 31 36 31 70 84 21 88 12 81]
[12 31 36 31 70 84 21 88 12 81]
[12 12 36 31 70 84 21 88 12 81]
[12 12 36 31 70 84 21 88 36 81]
[12 12 21 31 70 84 21 88 36 81]
[12 12 21 31 70 84 70 88 36 81]
[12 12 21 31 70 84 70 88 36 81]
[12 12 21 31 70 84 70 88 36 81]
[12 12 21 31 31 84 70 88 36 81]
[12 12 21 31 31 84 70 88 36 81]
[12 12 21 31 31 84 70 88 36 81]
[12 12 21 31 31 84 70 88 36 81]
[12 12 21 31 31 81 70 88 36 81]
[12 12 21 31 31 81 70 88 36 88]
[12 12 21 31 31 81 70 36 36 88]
[12 12 21 31 31 81 70 36 36 88]
[12 12 21 31 31 36 70 36 84 88]
[12 12 21 31 31 36 70 36 84 88]
[12 12 21 31 31 36 70 81 84 88]
[12 12 21 31 31 36 70 81 84 88]


array([12, 12, 21, 31, 31, 36, 70, 81, 84, 88])