# 排序

素材：
1. [史上最简单十大排序算法（Python实现）](https://blog.csdn.net/weixin_41571493/article/details/81875088)
2. [Python实现十大经典排序算法](https://www.jianshu.com/p/bbbab7fa77a2)
3. [Python实现十三大查找和排序算法](https://blog.csdn.net/Asher117/article/details/89500637)
4. [All Algorithms implemented in Python](https://github.com/TheAlgorithms/Python)

## 排序的分类 与 相关概念

**是否使用额外空间**：
- 内部排序：只使用内存
- 外部排序：内存和外存同时使用

**时间复杂度**：
- 非线性时间比较类排序：通过比较来决定元素间的相对次序，由于其时间复杂度不能突破O(nlogn)，因此称为非线性时间比较类排序、
- 线性时间非比较类排序： 不通过比较来决定元素间的相对次序，它可以突破基于比较排序的时间下界，以线性时间运行，因此称为线性时间非比较类排序。

**相关概念：**
- 稳定：如果a=b，排序不改变他们原始的次序
- 时间复杂度：对于排序数据的总的操作次数与n的关系
- 空间复杂度：算法执行时所需要的储存空间大小与n的关系

### 冒泡排序 Bubble Sort

> 思想：
1. 比较相邻的元素，如果第一个比第二个更大，那么交换他们两
2. 对每一对相邻的元素做同样的操作，从最开始的前两个数，到最后两个数。这样排在最后的数会是整个数列中最大的
3. 对数列重复以上操作，排除最后一个已经被排好序的数字。
4. 重复1-3，直到排序完成

冒泡排序对n个数据操作n-1轮，每一轮能找到一个最大值。

操作只对相邻两个数进行比较与交换，每一轮能把最值交换到数据的列尾，就像冒泡一样。

每一轮操作O(n)次，共O(n)轮，所以时间复杂度是O(n^2)

额外空间开销出现在交换数据的时候，需要一个过渡空间，空间复杂度是O(1)

In [3]:
import numpy as np
def BubbleSort(arr):
    n = len(arr)
    if n <= 1:
        return arr
    else:
        for i in range(n):
            for j in range(n-i-1):
                if arr[j] > arr[j+1]:
                    arr[j+1],arr[j] = arr[j],arr[j+1]
        return arr

In [67]:
def test_case(method,arr,**kwargs):
    print('排序前的数列：\n',np.array(arr))
    print('排序后的数列：\n',np.array(method(arr,**kwargs)))
    

In [5]:
test_case(BubbleSort,[1, 3, 4, -1])

排序前的数列：
 [ 1  3  4 -1]
排序后的数列：
 [-1  1  3  4]


### 快速排序 Quick Sort

> 思想
- 从数列中挑选一个元素，称为基准(pivot)
- 重新排序数列，所有比基准值小的元素摆放在基准的前面，所有比基准值大的元素摆放在基准的后面，相同的数可以摆放到任意一边。在这个分区退出之后，该基准就处于数列的中间位置。这个称为分区(partition)操作
- 递归地把小于基准的子数列和大于基准的子数列进行排序

快速排序基于选择划分，是简单选择排序的优化。

每次划分将数据宣导基准值的两边，然后递归对于两侧的数据进行划分，类似于二分法。

算法的整体性能取决于划分的平均程度，也即基准值的选择，从而衍生出快速排序的很多优化方案，甚至可以划分成多块。

基准值如果能把数据分为平均的两块，划分数为O(logn)，每次划分遍历一遍需要O(n)，时间复杂度是O(nlogn)

额外空间需要储存基准值，O(logn)次划分需要O(logn)个，空间复杂度O(logn)

In [6]:
# 空间复杂度O(nlogn)
def QuickSort(arr):
    if len(arr) <= 1:
        return arr
    else:
        mid = arr[0]
        left = [i for i in arr[1:] if i <= mid]
        right = [i for i in arr[1:] if i > mid]
        return QuickSort(left) + [mid] + QuickSort(right)

In [7]:
test_case(QuickSort,arr = list(np.random.randint(0,1000,size = 10)))

排序前的数列：
 [667 146 631  40 453 987 918 975 775 233]
排序后的数列：
 [ 40 146 233 453 631 667 775 918 975 987]


In [45]:
def QuickSort2(nums,left,right):
    def partition(nums,left,right):
        # 选取一个基准值，这边默认是第一个元素，有很多种优化方式
        pivot = nums[left]
        
        """
        对于这个基准值，把小于等于基准的数挪到前方，大于等于基准的数挪到后方。
        每个while循环里面，至多只能挪动一对数。
        left < right表示终止条件，right指的是第一个小于基准的位置，
        left指的是第一个大于等于基准的位置。如果left<right，表示对于这个基准来说，
        数列已经被排好了。
        """
        while left < right: 
            while left < right and nums[right] >= pivot:
                right -= 1 # 从右边开始，第一个小于基准的数的位置
            nums[left] = nums[right] # 把这个小于基准的数，放在序列的第一位
            while left < right and nums[left] < pivot:
                left += 1 # 从左边开始，第一个大于等于基准的数的位置
            nums[right] = nums[left] # 把这个大于等于基准的数，放在序列中right的位置
        nums[left] = pivot # 把基准值放在它应该在的位置 
        return left
        
    # 对于子序列递归
    if left < right:
        pivotIndex = partition(nums, left, right)
        QuickSort2(nums, left, pivotIndex - 1)
        QuickSort2(nums, pivotIndex + 1, right)
    return nums
        

In [73]:
test_case(QuickSort2,arr = list(np.random.randint(0,1000,size = 10)),left = 0,right = 9)

排序前的数列：
 [380 397 152 894 185 636 814 724 595 432]
排序后的数列：
 [152 185 380 397 432 595 636 724 814 894]


In [78]:
def print_kwargs(**kwargs):
        print(kwargs)

print_kwargs(kwargs_1="Shark", kwargs_2=4.5, kwargs_3=True)

{'kwargs_1': 'Shark', 'kwargs_2': 4.5, 'kwargs_3': True}


In [79]:
def print_args(*args):
    print(args[0])

print_args(1,2,3)

1


### 插入排序

>思想

- 从第一个元素开始，认为该元素已经被排序好了
- 取出下一个元素，在已经排序好的元素序列中从后往前扫描
- 如果排序好的元素大于新元素，那么再继续向前比较
- 直到找到已排序的序列中，小于等于该新元素的元素位置
- 将新元素插入该位置后
- 重复步骤2-5

简单插入排操作n-1轮，每一轮将一个未排序的数字插入排好序的序列中。

插入的操作包括：比较插入的位置，数据移位腾出合适的空位

每一轮操作O(n)次，共O(n)轮，所以时间复杂度O(n^2)

空间开销出在数据移动的过渡空间，O(1)



In [ ]:
def insertionSort(nums):
    for i in range(len(nums) - 1):  # 遍历 len(nums)-1 次
        curNum, preIndex = nums[i+1], i  # curNum 保存当前待插入的数
        while preIndex >= 0 and curNum < nums[preIndex]: # 将比 curNum 大的元素向后移动
            nums[preIndex + 1] = nums[preIndex]
            preIndex -= 1
        nums[preIndex + 1] = curNum  # 待插入的数的正确位置   
    return nums

In [ ]:
def InsertSort(lst):
    n=len(lst)
    if n<=1:
        return lst
    for i in range(1,n):
        j=i
        target=lst[i]            #每次循环的一个待插入的数
        while j>0 and target<lst[j-1]:       #比较、后移，给target腾位置
            lst[j]=lst[j-1]
            j=j-1
        lst[j]=target            #把target插到空位


In [248]:
nums = [77,4,20,90,36,12,7,50,48]
for i in range(1,len(nums)):
    current = nums[i]
    j = i
    while(j>0 and current<nums[j-1]):
        nums[j] = nums[j-1]
        j = j -1
    nums[j] = current
    print(nums)

[4, 77, 20, 90, 36, 12, 7, 50, 48]
[4, 20, 77, 90, 36, 12, 7, 50, 48]
[4, 20, 77, 90, 36, 12, 7, 50, 48]
[4, 20, 36, 77, 90, 12, 7, 50, 48]
[4, 12, 20, 36, 77, 90, 7, 50, 48]
[4, 7, 12, 20, 36, 77, 90, 50, 48]
[4, 7, 12, 20, 36, 50, 77, 90, 48]
[4, 7, 12, 20, 36, 48, 50, 77, 90]


In [244]:
def InsertSort(arr):
    n = len(arr)
    for i in range(1,n):
        # 给第i个数字进行排序
        num_now = arr[i]
        for j in range(i-1,-1,-1):
            if num_now >= arr[j]:
                pos = j+1
                break
            else:
                pos = 0
        arr[(pos + 1):(i + 1)] = arr[(pos):i]
        arr[pos] = num_now
    return arr
            
            

In [247]:
InsertSort([0,0,0,1,1,2,-1])

[-1, 0, 0, 0, 1, 1, 2]

what will happen? if we excute:

>```
num = [1,2,3,4]
num[0:2],num[2:4] = num[2:4],num[0:2]
```

### 希尔排序
> 思想
- 选择一个递减到1的增量序列，$\mathrm T = t_1 > \cdots >t_k > \cdots >t_K$,比如5,3,1
- 对于每个$t_k$，对原序列进行K次排序
- 每次排序中，根据$t_k$的值，将序列分割成长度为m的子序列，每个子序列进行插入排序，只改变子序列的元素相对位置。当增量因子为1的时候，相当于对所有元素进行插入排序

希尔排序是插入排序的高效实现，因为能够减少插入排序的移动次数。

简单插入排序每次插入都要移动大量数据，如果能一步到位，移动效率会高一些。

如果序列是基本有序的，插入排序不必移动多次，效率会比较高。

希尔排序将序列按照不同的间隔划分成子序列，在子序列中进行插入排序。相当于先远距离移动，使得序列基本有序。然后逐步减小间隔，最后间隔为1的时候进行一次插入排序。

希尔排序对序列划分O(n)次，每次插入排序O(logn)，时间复杂度O(nlogn)

额外的空间开销是由于插入过程中，数据移动需要一个暂存，空间复杂度O(1)



In [255]:

def ShellSort(lst):
    def shellinsert(arr,d):
        n=len(arr)
        for i in range(d,n):
            j=i-d
            temp=arr[i]             #记录要出入的数
            while(j>=0 and arr[j]>temp):    #从后向前，找打比其小的数的位置
                arr[j+d]=arr[j]                 #向后挪动
                j-=d
            if j!=i-d:
                arr[j+d]=temp
    n=len(lst)
    if n<=1:
        return lst
    d=n//2
    while d>=1:
        shellinsert(lst,d)
        d=d//2
    return lst

In [ ]:
def shellSort(nums):
    lens = len(nums)
    gap = 1  
    while gap < lens // 3:
        gap = gap * 3 + 1  # 动态定义间隔序列
    while gap > 0:
        for i in range(gap, lens):
            curNum, preIndex = nums[i], i - gap  # curNum 保存当前待插入的数
            while preIndex >= 0 and curNum < nums[preIndex]:
                nums[preIndex + gap] = nums[preIndex] # 将比 curNum 大的元素向后移动
                preIndex -= gap
            nums[preIndex + gap] = curNum  # 待插入的数的正确位置
        gap //= 3  # 下一个动态间隔
    return nums

In [312]:
def ShellSort(arr):
    def ShellInset(arr,d):
        """
        arr: list to be sorted
        d: T_k,the distance of each sub-list
        """
        n = len(arr)
        for i in range(n):
            now_num = arr[i]
            for j in range(i-d, -1, -d):
                if arr[j] > now_num:
                    arr[j+d] = arr[j]
                    arr[j] = now_num
                else:
                    break
        return arr
    n = len(arr)
    d = n // 2
    
    while d >= 1:
        arr = ShellInset(arr,d)
        d //= 2
    return arr
        

In [315]:
test_case(method = ShellSort, arr = np.random.randint(0,100,10))

排序前的数列：
 [56 44 96 18 88 28 29 38  1  5]
排序后的数列：
 [ 1  5 18 28 29 38 44 56 88 96]


### 简单选择排序
> 思想
- 